// Official Galinka Product Catalogue and Categories specification
export const CATEGORIES = [
  { slug: "domashni-kovbasy", name: "Домашні ковбаси", icon: "🌭", sort_order: 1 },
  { slug: "kopchene-myaso", name: "Копчене м’ясо", icon: "🥩", sort_order: 2 },
  { slug: "kuryache-kopchene", name: "Куряче копчене", icon: "🍗", sort_order: 3 },
  { slug: "vareni-kovbasy", name: "Варені ковбаси", icon: "🥓", sort_order: 4 },
  { slug: "sardelky-ta-kovbasky", name: "Сардельки та ковбаски", icon: "🌭", sort_order: 5 },
  { slug: "inshe", name: "Інше", icon: "🍲", sort_order: 6 },
  { slug: "pashtetky", name: "Паштетки", icon: "🥫", sort_order: 7 },
  { slug: "domashnye", name: "Домашнє", icon: "🧂", sort_order: 8 },
  { slug: "podarunkovi-boksy", name: "Подарункові бокси", icon: "🎁", sort_order: 9 },
];

export const PRODUCTS = [
  // 1. ДОМАШНІ КОВБАСИ
  {
    id: "prod_dk_1",
    slug: "kovbasa-lupana-domashnya",
    name: "Ковбаса лупана (домашня)",
    category: "domashni-kovbasy",
    weight: "1 кг",
    unit: "кг",
    price: 450,
    oldPrice: null,
    stock: 45,
    featured: true,
    giftBox: false,
    description: "Справжня українська домашня ковбаса лупана за родинним рецептом. Натуральна оболонка, свіжа свинина, часник, духмяні прянощі та легке запікання.",
    image: "kovbasa-domashnya",
  },
  {
    id: "prod_dk_2",
    slug: "kovbasa-rublena-fileyna",
    name: "Ковбаса рублена (філейна)",
    category: "domashni-kovbasy",
    weight: "1 кг",
    unit: "кг",
    price: 420,
    oldPrice: null,
    stock: 40,
    featured: true,
    giftBox: false,
    description: "Соковита рублена ковбаса з добірного свинячого філе. Виразна м'ясна фактура, делікатні спеції та виняткова соковитість.",
    image: "kovbasa-domashnya",
  },
  {
    id: "prod_dk_3",
    slug: "kovbasa-rublena-klub-fileyka",
    name: "Ковбаса рублена (клуб + філейка)",
    category: "domashni-kovbasy",
    weight: "1 кг",
    unit: "кг",
    price: 400,
    oldPrice: null,
    stock: 35,
    featured: false,
    giftBox: false,
    description: "Апетитна рублена ковбаса з комбінації соковитої стегнової частини та ніжної філейки. Збалансований та гармонійний смак.",
    image: "kovbasa-domashnya",
  },
  {
    id: "prod_dk_4",
    slug: "kovbasa-rublena-lopatka",
    name: "Ковбаса рублена (лопатка)",
    category: "domashni-kovbasy",
    weight: "1 кг",
    unit: "кг",
    price: 380,
    oldPrice: null,
    stock: 35,
    featured: false,
    giftBox: false,
    description: "Класична домашня ковбаса з рубаної свинячої лопатки з додаванням часничку та меленого перцю за традиційним народним рецептом.",
    image: "kovbasa-domashnya",
  },
  {
    id: "prod_dk_5",
    slug: "kovbasa-melena-z-salom",
    name: "Ковбаса мелена (з салом)",
    category: "domashni-kovbasy",
    weight: "1 кг",
    unit: "кг",
    price: 360,
    oldPrice: null,
    stock: 35,
    featured: false,
    giftBox: false,
    description: "Ніжна домашня мелена ковбаска з апетитними вкрапленнями свіжого сала. Дуже соковита, запашна та ситна.",
    image: "kovbasa-domashnya",
  },
  {
    id: "prod_dk_6",
    slug: "kovbasa-melena-bilshe-sala",
    name: "Ковбаса мелена більше сала",
    category: "domashni-kovbasy",
    weight: "1 кг",
    unit: "кг",
    price: 280,
    oldPrice: null,
    stock: 30,
    featured: false,
    giftBox: false,
    description: "Ситна домашня ковбаса зі щедрим додаванням сала та часнику. Ідеально підходить для смаження на пательні або запікання з картоплею.",
    image: "kovbasa-domashnya",
  },
  {
    id: "prod_dk_7",
    slug: "kovbasa-kuryacha-fileyna",
    name: "Ковбаса куряча філейна",
    category: "domashni-kovbasy",
    weight: "1 кг",
    unit: "кг",
    price: 380,
    oldPrice: null,
    stock: 35,
    featured: true,
    giftBox: false,
    description: "Дієтична та ніжна домашня ковбаса з чистих курячих грудок. Соковита, легка, без зайвого жиру, подобається дітям.",
    image: "kurochka",
  },
  {
    id: "prod_dk_8",
    slug: "kovbasa-pechena-kuryacha",
    name: "Ковбаса печена куряча",
    category: "domashni-kovbasy",
    weight: "1 кг",
    unit: "кг",
    price: 450,
    oldPrice: null,
    stock: 30,
    featured: true,
    giftBox: false,
    description: "Печена в печі куряча ковбаса до рум'яної скоринки. Натуральне м'ясо птиці, легкі спеції та вишуканий аромат домашньої випічки.",
    image: "kurochka",
  },
  {
    id: "prod_dk_9",
    slug: "kovbasa-pechena-svynya",
    name: "Ковбаса печена свиня",
    category: "domashni-kovbasy",
    weight: "1 кг",
    unit: "кг",
    price: 450,
    oldPrice: null,
    stock: 35,
    featured: true,
    giftBox: false,
    description: "Святкова печена домашня ковбаса зі свинини. Свіжий часник, сухі прянощі, золотиста оболонка та неперевершений смак свята.",
    image: "kovbasa-domashnya",
  },

  // 2. КОПЧЕНЕ М’ЯСО
  {
    id: "prod_km_1",
    slug: "balychok-kopchenyy",
    name: "Баличок копчений",
    category: "kopchene-myaso",
    weight: "1 кг",
    unit: "кг",
    price: 480,
    oldPrice: null,
    stock: 30,
    featured: true,
    giftBox: false,
    description: "Найніжніший свинячий баличок помірного соління, копчений на сухій вільсі. М'яка волокниста текстура, тонкий аромат натурального димка.",
    image: "balyk",
  },
  {
    id: "prod_km_2",
    slug: "oshyyok-yak-shashlyk",
    name: "Ошийок (як шашлик)",
    category: "kopchene-myaso",
    weight: "1 кг",
    unit: "кг",
    price: 480,
    oldPrice: null,
    stock: 30,
    featured: true,
    giftBox: false,
    description: "Мармуровий свинячий ошийок із насиченим смаком справжнього шашлику на дровах. Надзвичайно соковитий та ніжний.",
    image: "shynka",
  },
  {
    id: "prod_km_3",
    slug: "rulet-z-chornoslyvom",
    name: "Рулет з чорносливом",
    category: "kopchene-myaso",
    weight: "1 кг",
    unit: "кг",
    price: 480,
    oldPrice: null,
    stock: 25,
    featured: true,
    giftBox: false,
    description: "Вишуканий м'ясний рулет гарячого копчення з начинкою із солодкого в'яленого чорносливу. Чудово прикрашає святковий стіл.",
    image: "shynka",
  },
  {
    id: "prod_km_4",
    slug: "rulet-z-kurahoyu",
    name: "Рулет з курагою",
    category: "kopchene-myaso",
    weight: "1 кг",
    unit: "кг",
    price: 480,
    oldPrice: null,
    stock: 25,
    featured: false,
    giftBox: false,
    description: "М'ясний делікатесний рулет із добірною курагою. Ніжне м'ясо з димком та пікантний фруктовий посмак.",
    image: "shynka",
  },
  {
    id: "prod_km_5",
    slug: "pidcherevyna-kopchena",
    name: "Підчеревина",
    category: "kopchene-myaso",
    weight: "1 кг",
    unit: "кг",
    price: 450,
    oldPrice: null,
    stock: 35,
    featured: true,
    giftBox: false,
    description: "Багаті м'ясні прошарки, тануче сало та рум'яна копчена скоринка. Традиційне українське копчення на фруктових та вільхових дровах.",
    image: "pidcherevyna",
  },
  {
    id: "prod_km_6",
    slug: "salo-kopchene",
    name: "Сало копчене",
    category: "kopchene-myaso",
    weight: "1 кг",
    unit: "кг",
    price: 250,
    oldPrice: null,
    stock: 40,
    featured: false,
    giftBox: false,
    description: "Ароматне сало гарячого копчення на дровах. М'яке, як масло, з гарним золотистим кольором та чистим димним запахом.",
    image: "salo",
  },
  {
    id: "prod_km_7",
    slug: "rebertsya-kopcheni",
    name: "Реберця",
    category: "kopchene-myaso",
    weight: "1 кг",
    unit: "кг",
    price: 300,
    oldPrice: null,
    stock: 30,
    featured: true,
    giftBox: false,
    description: "М'ясисті соковиті свинячі ребра гарячого копчення. Неперевершений аромат, смакують самостійно або до домашнього борщу.",
    image: "rebertsya",
  },

  // 3. КУРЯЧЕ КОПЧЕНЕ
  {
    id: "prod_kk_1",
    slug: "kurka-kopchena",
    name: "Курка копчена",
    category: "kuryache-kopchene",
    weight: "1 кг",
    unit: "кг",
    price: 300,
    oldPrice: null,
    stock: 30,
    featured: true,
    giftBox: false,
    description: "Ціла соковита курочка гарячого копчення на вільсі. Золотава хрумка шкірочка та ніжне, просочене димком м'ясо.",
    image: "kurochka",
  },
  {
    id: "prod_kk_2",
    slug: "okorochok-kopchenyy",
    name: "Окорочок",
    category: "kuryache-kopchene",
    weight: "1 кг",
    unit: "кг",
    price: 280,
    oldPrice: null,
    stock: 35,
    featured: false,
    giftBox: false,
    description: "Апетитний курячий окорочок гарячого копчення. Соковитий, м'який та з насиченим смаком домашнього диму.",
    image: "kurochka",
  },
  {
    id: "prod_kk_3",
    slug: "kryla-kopcheni",
    name: "Крила",
    category: "kuryache-kopchene",
    weight: "1 кг",
    unit: "кг",
    price: 280,
    oldPrice: null,
    stock: 30,
    featured: false,
    giftBox: false,
    description: "Золотисті курячі крильця з делікатним копченням. Ідеальна закуска для компанії та святкового частування.",
    image: "kurochka",
  },
  {
    id: "prod_kk_4",
    slug: "file-kuryache-kopchene",
    name: "Філе",
    category: "kuryache-kopchene",
    weight: "1 кг",
    unit: "кг",
    price: 380,
    oldPrice: null,
    stock: 30,
    featured: true,
    giftBox: false,
    description: "Добірне копчене куряче філе без кісток та шкіри. М'яке, не сухе, з вишуканими прянощами.",
    image: "kurochka",
  },
  {
    id: "prod_kk_5",
    slug: "rulety-kuryachi",
    name: "Рулети курячі",
    category: "kuryache-kopchene",
    weight: "1 кг",
    unit: "кг",
    price: 380,
    oldPrice: null,
    stock: 25,
    featured: true,
    giftBox: false,
    description: "Ніжні домашні курячі рулети гарячого копчення. Тонко нарізаються для вишуканої м'ясної тарілки.",
    image: "kurochka",
  },

  // 4. ВАРЕНІ КОВБАСИ
  {
    id: "prod_vk_1",
    slug: "kovbasa-molochna",
    name: "Молочна",
    category: "vareni-kovbasy",
    weight: "1 кг",
    unit: "кг",
    price: 250,
    oldPrice: null,
    stock: 35,
    featured: true,
    giftBox: false,
    description: "Класична домашня молочна варена ковбаса. Ніжна кремова структура, натуральне молоко, свіже м'ясо без фосфатів.",
    image: "sardelky",
  },
  {
    id: "prod_vk_2",
    slug: "kovbasa-nizhna",
    name: "Ніжна",
    category: "vareni-kovbasy",
    weight: "1 кг",
    unit: "кг",
    price: 200,
    oldPrice: null,
    stock: 35,
    featured: false,
    giftBox: false,
    description: "Легка варена ковбаса з помірною пряністю. Створена для легких сніданків, салатів та бутербродів.",
    image: "sardelky",
  },
  {
    id: "prod_vk_3",
    slug: "kovbasa-fileyna-varena",
    name: "Філейна",
    category: "vareni-kovbasy",
    weight: "1 кг",
    unit: "кг",
    price: 300,
    oldPrice: null,
    stock: 30,
    featured: true,
    giftBox: false,
    description: "Преміальна варена ковбаса з чистого філе. Пружна, м'ясна, бездоганна на смак.",
    image: "sardelky",
  },

  // 5. САРДЕЛЬКИ ТА КОВБАСКИ
  {
    id: "prod_sk_1",
    slug: "sardelky-molochni",
    name: "Молочні",
    category: "sardelky-ta-kovbasky",
    weight: "1 кг",
    unit: "кг",
    price: 250,
    oldPrice: null,
    stock: 40,
    featured: true,
    giftBox: false,
    description: "Соковиті домашні молочні сардельки у тонкій натуральній оболонці. При варінні лопаються соком.",
    image: "sardelky",
  },
  {
    id: "prod_sk_2",
    slug: "sardelky-nizhni",
    name: "Ніжні",
    category: "sardelky-ta-kovbasky",
    weight: "1 кг",
    unit: "кг",
    price: 200,
    oldPrice: null,
    stock: 35,
    featured: false,
    giftBox: false,
    description: "М'які ніжні сардельки з відбірного фермерського м'яса зі свіжими приправами.",
    image: "sardelky",
  },
  {
    id: "prod_sk_3",
    slug: "sardelky-fileyni",
    name: "Філейні",
    category: "sardelky-ta-kovbasky",
    weight: "1 кг",
    unit: "кг",
    price: 300,
    oldPrice: null,
    stock: 30,
    featured: true,
    giftBox: false,
    description: "Сардельки вищого ґатунку з добірного філе. М'ясисті, пружні та надзвичайно смачні.",
    image: "sardelky",
  },
  {
    id: "prod_sk_4",
    slug: "pechinkovi-kovbasky",
    name: "Печінкові ковбаски",
    category: "sardelky-ta-kovbasky",
    weight: "1 кг",
    unit: "кг",
    price: 120,
    oldPrice: null,
    stock: 30,
    featured: false,
    giftBox: false,
    description: "Традиційні домашні ковбаски зі свіжої печінки з цибулькою та спеціями за старовинним рецептом.",
    image: "pashtet",
  },
  {
    id: "prod_sk_5",
    slug: "liverna-kovbasa",
    name: "Ліверна ковбаса",
    category: "sardelky-ta-kovbasky",
    weight: "1 кг",
    unit: "кг",
    price: 120,
    oldPrice: null,
    stock: 30,
    featured: false,
    giftBox: false,
    description: "Справжня домашня ліверна ковбаса з чистих натуральних складників. Ніжна текстура та багатий смак.",
    image: "pashtet",
  },
  {
    id: "prod_sk_6",
    slug: "sardelky-kopcheni",
    name: "Сардельки копчені",
    category: "sardelky-ta-kovbasky",
    weight: "1 кг",
    unit: "кг",
    price: 200,
    oldPrice: null,
    stock: 35,
    featured: true,
    giftBox: false,
    description: "Ароматні сардельки гарячого копчення на вільхових дровах. Хрумка натуральна оболонка та соковитий м'ясний смак.",
    image: "sardelky",
  },
  {
    id: "prod_sk_7",
    slug: "sardelky-tsyharky",
    name: "Сардельки цигарки",
    category: "sardelky-ta-kovbasky",
    weight: "1 кг",
    unit: "кг",
    price: 200,
    oldPrice: null,
    stock: 35,
    featured: false,
    giftBox: false,
    description: "Тонкі подовжені домашні ковбаски-цигарки. Зручний формат для швидкого перекусу чи смаження на вогні.",
    image: "sardelky",
  },
  {
    id: "prod_sk_8",
    slug: "myslyvski-kovbasky",
    name: "Мисливські ковбаски",
    category: "sardelky-ta-kovbasky",
    weight: "1 кг",
    unit: "кг",
    price: 250,
    oldPrice: null,
    stock: 40,
    featured: true,
    giftBox: false,
    description: "Пікантні напівкопчені мисливські ковбаски з часником та чорним перцем. Пружні, з димним ароматом.",
    image: "kovbasa-kopchena",
  },
  {
    id: "prod_sk_9",
    slug: "kovbasky-khot-doh",
    name: "Ковбаски хот-дог",
    category: "sardelky-ta-kovbasky",
    weight: "1 кг",
    unit: "кг",
    price: 250,
    oldPrice: null,
    stock: 35,
    featured: false,
    giftBox: false,
    description: "Спеціальні ніжні м'ясні ковбаски ідеальної форми для домашніх хот-догів та бутербродів.",
    image: "sardelky",
  },

  // 6. ІНШЕ
  {
    id: "prod_in_1",
    slug: "shashlyk-kuryachyy-hryl",
    name: "Шашлик курячий (на грилі)",
    category: "inshe",
    weight: "1 кг",
    unit: "кг",
    price: 300,
    oldPrice: null,
    stock: 25,
    featured: true,
    giftBox: false,
    description: "Замаринований за секретним родинним рецептом та обсмажений на грилі соковитий курячий шашлик.",
    image: "kurochka",
  },
  {
    id: "prod_in_2",
    slug: "shynka-svynyna-kurka",
    name: "Шинка (свинина + курка)",
    category: "inshe",
    weight: "1 кг",
    unit: "кг",
    price: 400,
    oldPrice: null,
    stock: 30,
    featured: true,
    giftBox: false,
    description: "Соковита домашня шинка з добірної нежирної свинини та соковитої курки. Прекрасний візерунок на зрізі та делікатний смак.",
    image: "shynka",
  },

  // 7. ПАШТЕТКИ
  {
    id: "prod_pt_1",
    slug: "pashtet-kuryachyy",
    name: "Курячий (філе + окорочок)",
    category: "pashtetky",
    weight: "350 г",
    unit: "шт",
    price: 220,
    oldPrice: null,
    stock: 35,
    featured: true,
    giftBox: false,
    description: "Ніжний кремовий паштет з курячого філе та окорочка, запечений з морквою, цибулею та вершковим маслом.",
    image: "pashtet",
  },
  {
    id: "prod_pt_2",
    slug: "pashtet-pechinkovyy-svynyachyy",
    name: "Печінковий свинячий (печінка + м’ясо)",
    category: "pashtetky",
    weight: "350 г",
    unit: "шт",
    price: 220,
    oldPrice: null,
    stock: 35,
    featured: true,
    giftBox: false,
    description: "Традиційний запечений паштет зі свіжої свинячої печінки та м'яса. Справжня домашня класика.",
    image: "pashtet",
  },
  {
    id: "prod_pt_3",
    slug: "saltyson-yazykovyy",
    name: "Сальтисон язиковий",
    category: "pashtetky",
    weight: "1 кг",
    unit: "кг",
    price: 300,
    oldPrice: null,
    stock: 25,
    featured: true,
    giftBox: false,
    description: "Шляхетний домашній сальтисон із відвареним свинячим язиком, часничком та духмяним перцем.",
    image: "shynka",
  },
  {
    id: "prod_pt_4",
    slug: "pechene-myaso",
    name: "Печене м’ясо",
    category: "pashtetky",
    weight: "1 кг",
    unit: "кг",
    price: 480,
    oldPrice: null,
    stock: 25,
    featured: true,
    giftBox: false,
    description: "Цілісний шматок свинини, запечений за традиційним домашнім рецептом до соковитості та золотої скоринки.",
    image: "balyk",
  },
  {
    id: "prod_pt_5",
    slug: "pechenyy-rulet",
    name: "Печений рулет",
    category: "pashtetky",
    weight: "1 кг",
    unit: "кг",
    price: 480,
    oldPrice: null,
    stock: 25,
    featured: false,
    giftBox: false,
    description: "Домашній м'ясний рулет зі спеціями, повільно випечений у печі до ідеальної м'якості.",
    image: "shynka",
  },
  {
    id: "prod_pt_6",
    slug: "oshyyok-pechenyy",
    name: "Ошийок печений",
    category: "pashtetky",
    weight: "1 кг",
    unit: "кг",
    price: 480,
    oldPrice: null,
    stock: 25,
    featured: true,
    giftBox: false,
    description: "Соковитий свинячий ошийок тривалого запікання з часником та пряними травами.",
    image: "shynka",
  },
  {
    id: "prod_pt_7",
    slug: "kovbasovyy-syr",
    name: "Ковбасовий сир",
    category: "pashtetky",
    weight: "1 кг",
    unit: "кг",
    price: 300,
    oldPrice: null,
    stock: 30,
    featured: false,
    giftBox: false,
    description: "Натуральний копчений ковбасний сир із золотистою скоринкою та вершково-димним присмаком.",
    image: "kovbasa-kopchena",
  },

  // 8. ДОМАШНЄ
  {
    id: "prod_dm_1",
    slug: "salo-domashnye",
    name: "Сало",
    category: "domashnye",
    weight: "1 кг",
    unit: "кг",
    price: 350,
    oldPrice: null,
    stock: 40,
    featured: true,
    giftBox: false,
    description: "Справжнє добірне українське домашнє сало сухого засолу з часничком, перцем та пряними спеціями.",
    image: "salo",
  },
  {
    id: "prod_dm_2",
    slug: "solonyna",
    name: "Солонина",
    category: "domashnye",
    weight: "1 кг",
    unit: "кг",
    price: 350,
    oldPrice: null,
    stock: 30,
    featured: true,
    giftBox: false,
    description: "Традиційна українська солонина витриманого сухого посолу. М'яка, пружна, неперевершено смакує з чорним хлібом.",
    image: "salo",
  },

  // 9. ПОДАРУНКОВІ БОКСИ (ГОТОВІ НАБОРИ)
  {
    id: "box_myasnyy",
    slug: "boks-myasnyy",
    name: "М’ясний бокс",
    category: "podarunkovi-boksy",
    weight: "набір (~2.5 кг)",
    unit: "набір",
    price: 1200,
    oldPrice: null,
    stock: 20,
    featured: true,
    giftBox: true,
    description: "Добірний асорті-бокс кращих м'ясних делікатесів: домашня ковбаса, баличок копчений, рулет та свіже сало у подарунковій крафтовій коробці.",
    image: "prod-gift-box",
    boxItems: JSON.stringify([
      { name: "Ковбаса лупана (домашня)", qty: 1 },
      { name: "Баличок копчений", qty: 1 },
      { name: "Сало копчене", qty: 1 },
    ]),
  },
  {
    id: "box_do_svyata",
    slug: "boks-do-svyata",
    name: "Бокс до свята",
    category: "podarunkovi-boksy",
    weight: "набір (~3 кг)",
    unit: "набір",
    price: 1500,
    oldPrice: null,
    stock: 20,
    featured: true,
    giftBox: true,
    description: "Святковий набір до столу: ковбаса рублена філейна, ошийок (як шашлик), рулет з чорносливом та язиковий сальтисон.",
    image: "prod-gift-box",
    boxItems: JSON.stringify([
      { name: "Ковбаса рублена (філейна)", qty: 1 },
      { name: "Ошийок (як шашлик)", qty: 1 },
      { name: "Рулет з чорносливом", qty: 1 },
      { name: "Сальтисон язиковий", qty: 1 },
    ]),
  },
  {
    id: "box_viyskovy",
    slug: "boks-dlya-viyskovoho",
    name: "Бокс для військового",
    category: "podarunkovi-boksy",
    weight: "набір (~2.8 кг)",
    unit: "набір",
    price: 1350,
    oldPrice: null,
    stock: 20,
    featured: true,
    giftBox: true,
    description: "Поживний, ситний та тривалого зберігання набір: домашня ковбаса, солонина, копчене сало, мисливські ковбаски та запечений паштет у вакуумній термоупаковці.",
    image: "prod-gift-box",
    boxItems: JSON.stringify([
      { name: "Ковбаса лупана (домашня)", qty: 1 },
      { name: "Солонина", qty: 1 },
      { name: "Сало копчене", qty: 1 },
      { name: "Мисливські ковбаски", qty: 1 },
      { name: "Печінковий свинячий", qty: 1 },
    ]),
  },
  {
    id: "box_simeynyy",
    slug: "boks-simeynyy",
    name: "Сімейний бокс",
    category: "podarunkovi-boksy",
    weight: "набір (~3.2 кг)",
    unit: "набір",
    price: 1400,
    oldPrice: null,
    stock: 20,
    featured: true,
    giftBox: true,
    description: "Великий смачний набір для всієї родини: варена молочна ковбаса, курячий рулет, баличок, ніжні сардельки та паштет.",
    image: "prod-gift-box",
    boxItems: JSON.stringify([
      { name: "Молочна", qty: 1 },
      { name: "Баличок копчений", qty: 1 },
      { name: "Рулети курячі", qty: 1 },
      { name: "Молочні сардельки", qty: 1 },
      { name: "Курячий паштет", qty: 1 },
    ]),
  },
  {
    id: "box_podarunkovyy",
    slug: "boks-podarunkovyy",
    name: "Подарунковий бокс",
    category: "podarunkovi-boksy",
    weight: "набір (~3.5 кг)",
    unit: "набір",
    price: 1600,
    oldPrice: null,
    stock: 20,
    featured: true,
    giftBox: true,
    description: "Преміальний набір делікатесів у святковому крафтовому пакуванні: баличок, печене м'ясо, рулет з курагою, ковбаса печена свиня та ковбасний сир.",
    image: "prod-gift-box",
    boxItems: JSON.stringify([
      { name: "Баличок копчений", qty: 1 },
      { name: "Печене м’ясо", qty: 1 },
      { name: "Рулет з курагою", qty: 1 },
      { name: "Ковбаса печена свиня", qty: 1 },
      { name: "Ковбасовий сир", qty: 1 },
    ]),
  },

  // 10. ВЛАСНИЙ ПОДАРУНКОВИЙ БОКС (ДЛЯ КОНСТРУКТОРА)
  {
    id: "custom_box",
    slug: "vlasnyy-podarunkovyy-boks",
    name: "Власний подарунковий бокс",
    category: "podarunkovi-boksy",
    weight: "набір",
    unit: "набір",
    price: 0,
    oldPrice: null,
    stock: 9999,
    featured: false,
    giftBox: true,
    description: "Індивідуальний подарунковий бокс, зібраний покупцем у нашому онлайн-конструкторі.",
    image: "prod-gift-box",
    boxItems: "[]",
  },
];

export const DEFAULT_INTERNATIONAL_SETTINGS = {
  enabled: true,
  countries: "Польща, Німеччина, Чехія, Італія, Іспанія, Молдова, Литва, Латвія, Естонія, Румунія та інші країни Європи",
  deliveryMethod: "Міжнародний перевізник (Нова Пошта Global / Meest / адресний бус)",
  cost: "За тарифами міжнародного перевізника",
  terms: "5–10 робочих днів у вакуумній термоупаковці з холодоелементами",
  minOrderAmount: 1000,
  infoText: "Доставка за кордон здійснюється перевізниками (Нова Пошта Global, Meest або пряма адресна доставка). Усі м'ясні вироби герметично вакуюються та пакуються у термобокси з акумуляторами холоду, що гарантує збереження свіжості. Після оформлення замовлення наш менеджер зв'яжеться з вами у Viber або за телефоном для узгодження адреси, тарифу та найзручнішого способу відправки.",
};
